Feature/garrett-lam/aliciadaniellet/personal information
TritonSE/TSE-Application-Form pull request #13
Opened 2022-05-13 21:40 UTC by garrett-lam

### Administrative Info
[GitHub Issue #1 ] 
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- personal information backbone

### Testing
How did you confirm your changes worked? 
- looked at it on npm start

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![Screenshot 2022-05-13 at 2 37 59 PM](https://user-images.githubusercontent.com/94739295/168392876-a1824755-85fb-4496-99c7-aef36248cd18.png)

2022-05-14 16:33 UTC, EShults2124 approved these changes
Looks good!

2022-05-14 16:53 UTC, StephenTan12 commented
Hi! Great work for your very first PR! Logic-wise, this is great and looks good. There are just some things regarding the consistency of the code and the format the code it is in that needs to be changed.

2022-05-14 16:53 UTC, StephenTan12 requested changes

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +import 'bootstrap/dist/css/bootstrap.min.css';
use double quotes instead of single quotes to ensure consistency.

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            </Form.Control>
Change all of the <Form.Control> elements to be...
![image](https://user-images.githubusercontent.com/69172929/168441176-63cd95b4-7f61-459a-8a0a-523a4a6f8059.png)

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            onChange={(e) => {changePersonalInfo("email", e.target.value)}}>
here too

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            </Form.Control>
here

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            </Form.Control>
here

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            onChange={(e) => {changePersonalInfo("graduation quarter", e.target.value)}}>
here

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            onChange={(e) => {changePersonalInfo("graduation year", e.target.value)}}>
here

2022-05-14 16:53 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +          onChange={(e) => {changePersonalInfo("resume", e.target.value)}}>
here

2022-05-15 17:55 UTC, StephenTan12 requested changes

2022-05-15 17:55 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            </Form.Control>
align the curly braces to the start of the onChange

2022-05-15 17:55 UTC, StephenTan12 commented on frontend/src/components/ApplicationForm.jsx
> +            </Form.Control>
do the same thing for the rest of the onChange handlers

2022-05-16 21:30 UTC, StephenTan12 approved these changes
LGTM

2022-05-16 21:30 UTC, merged